### ISSUE TITLE
ETL update or create

### ISSUE THREAD

**Issue by thomas-fred** [nismod/infra-risk-vis#163]
Metadata creation in postgres:
Allow for create _or_ update operation when posting to `backend` to create table metadata in `postgreSQL`, currently this operation returns 4XX if the table metadata already exists.

**Comment by tomalrussell** [comment]
ETL now works against the database directly rather than via the backend API.

See notes in README on dropping terracotta metadata databases before ingesting raster layers (the `ingest.py` script will keep going if the database already exists and just try skipping any already-ingested layers).

The `ingest_metadata.py` script will now delete any rows from `raster_tile_sources` with the current `domain` before attempting an insert, which is effectively create or (delete then create) update.
