### ISSUE TITLE
Improve map layer symbology - distinguish assets by colour (e.g. water/wastewater)

### ISSUE THREAD

**Issue by tomalrussell** [nismod/infra-risk-vis#30]

**Comment by mz8i** [comment]
Another symbology change that would be especially beneficial in the direct damages view, would be to differentiate not only the colour, but also the shape of point features.

For example: power generation node - diamond, power demand node - triangle, power junction - circle
Otherwise, when mapping damages, one needs to hover over point features to see which asset type they are.
